"""Initial tables

Revision ID: f963154b96cf
Revises: 
Create Date: 2026-01-06 18:35:54.700551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f963154b96cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_language', sa.String(length=10), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_format', sa.String(length=10), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_translation_rules',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('do_not_translate', sa.JSON(), nullable=False),
    sa.Column('preferred_translations', sa.JSON(), nullable=False),
    sa.Column('style', sa.Enum('FORMAL', 'NEUTRAL', 'FRIENDLY', name='translationstyle'), nullable=False),
    sa.Column('extra_rules', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('pptx_asset_path', sa.String(length=500), nullable=True),
    sa.Column('slides_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'RENDERING', 'DONE', 'FAILED', name='projectstatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_audio_settings',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('background_music_enabled', sa.Boolean(), nullable=False),
    sa.Column('music_asset_id', sa.UUID(), nullable=True),
    sa.Column('voice_gain_db', sa.Float(), nullable=False),
    sa.Column('music_gain_db', sa.Float(), nullable=False),
    sa.Column('ducking_enabled', sa.Boolean(), nullable=False),
    sa.Column('ducking_strength', sa.Enum('LIGHT', 'DEFAULT', 'STRONG', name='duckingstrength'), nullable=False),
    sa.Column('target_lufs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['music_asset_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('render_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=True),
    sa.Column('job_type', sa.Enum('CONVERT', 'TTS', 'RENDER', 'PREVIEW', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('logs_path', sa.String(length=500), nullable=True),
    sa.Column('output_video_path', sa.String(length=500), nullable=True),
    sa.Column('output_srt_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('notes_text', sa.Text(), nullable=True),
    sa.Column('slide_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slide_audio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slide_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('voice_id', sa.String(length=100), nullable=False),
    sa.Column('audio_path', sa.String(length=500), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('audio_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slide_scripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slide_id', sa.UUID(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'IMPORTED_NOTES', 'TRANSLATED', name='scriptsource'), nullable=False),
    sa.Column('translation_meta_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slide_scripts')
    op.drop_table('slide_audio')
    op.drop_table('slides')
    op.drop_table('render_jobs')
    op.drop_table('project_audio_settings')
    op.drop_table('project_versions')
    op.drop_table('project_translation_rules')
    op.drop_table('audio_assets')
    op.drop_table('projects')
    # ### end Alembic commands ###

